name: Fetch Bible Verse

on:
  workflow_dispatch

jobs:
  fetch-verse:
    runs-on: ubuntu-latest
    env:
      MY_API_KEY: ${{secrets.API_KEY}}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Bible Verse
      run: echo $MY_API_KEY